version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: westos
      MYSQL_DATABASE: clms
      MYSQL_USER: clms
      MYSQL_PASSWORD: clms_1
    deploy:
      restart_policy:
        condition: on-failure